services:
  postgres-db:
    image: postgres:15
    container_name: postgres-dnf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dnf_db
    ports:
      - "5432:5432"
    restart: always

  eureka-server:
    build: ./eurekaserver
    ports:
      - "8761:8761"

  ms-mascota:
    build: ./Ms-mascota
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres-db

  ms-usuario:
    build: ./Ms-usuario
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-db

  ms-coincidencias:
    build: ./Ms-coincidencias
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres-db

  api-gateway:
    build: ./Api-Gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  
  ms-comunidad:
    build: ./Ms-comunidad/Ms-comunidad
    ports:
      - "8094:8094"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dnf_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=adminpassword
    depends_on:
      - eureka-server
      - postgres-db

  ms-notificaciones:
    build: ./Ms-notificaciones/Ms-notificaciones
    ports:
      - "8095:8095"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server