server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      mvc:
        routes:
          - id: ms-usuario
            uri: lb://MS-USUARIO
            predicates:
              - Path=/api/usuarios/**
          - id: ms-mascota
            uri: lb://MS-MASCOTA
            predicates:
              - Path=/api/mascotas/**
          - id: ms-coincidencias
            uri: lb://MS-COINCIDENCIAS
            predicates:
              - Path=/api/coincidencias/**
          - id: ms-comunidad
            uri: lb://MS-COMUNIDAD
            predicates:
              - Path=/api/success-stories/**
          - id: ms-notificaciones
            uri: lb://MS-NOTIFICACIONES
            predicates:
              - Path=/api/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/