server.port=9090

# Rutas para Ms-usuario (puerto 8081)
spring.cloud.gateway.mvc.routes[0].id=usuarios-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/usuarios/**

# Rutas para Ms-mascota (puerto 8080)
spring.cloud.gateway.mvc.routes[1].id=mascotas-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8080
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/mascotas/**

# Rutas para Ms-coincidencias (puerto 8082)
spring.cloud.gateway.mvc.routes[2].id=coincidencias-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/coincidencias/**