server:
  port: 8095

spring:
  application:
    name: ms-notificaciones
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tu_usuario@gmail.com}
    password: ${MAIL_PASSWORD:tu_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/